// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJSIVIRd0iBpot7xQknRtkm67S5EntgM',
    appId: '1:348089054168:web:6369aab4be4ee1b0e478ad',
    messagingSenderId: '348089054168',
    projectId: 'tanvirhasan-flame-game-2025',
    authDomain: 'tanvirhasan-flame-game-2025.firebaseapp.com',
    storageBucket: 'tanvirhasan-flame-game-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBU8GADOf5DOTMcDG4X4vj7nnsXu1wal0',
    appId: '1:348089054168:android:1fa23c7f31406eb9e478ad',
    messagingSenderId: '348089054168',
    projectId: 'tanvirhasan-flame-game-2025',
    storageBucket: 'tanvirhasan-flame-game-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzkS5re8c-Ct3GhC8LkzJi1sc5IzA2pe0',
    appId: '1:348089054168:ios:736abb5327e3532ce478ad',
    messagingSenderId: '348089054168',
    projectId: 'tanvirhasan-flame-game-2025',
    storageBucket: 'tanvirhasan-flame-game-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterFaysalGame',
  );
}
