// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3esvgWciEk9F_rm4Ms9KIeuaKRmEoBxc',
    appId: '1:460415886376:web:38d6ff2b092cb90455811d',
    messagingSenderId: '460415886376',
    projectId: 'flutter-faysal-game-v2-32c09',
    authDomain: 'flutter-faysal-game-v2-32c09.firebaseapp.com',
    storageBucket: 'flutter-faysal-game-v2-32c09.firebasestorage.app',
    measurementId: 'G-9038TQWT4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbNOsc89hIn8YiIjSxxP0r90oPsQ3NbU',
    appId: '1:460415886376:android:78cf13404246c13455811d',
    messagingSenderId: '460415886376',
    projectId: 'flutter-faysal-game-v2-32c09',
    storageBucket: 'flutter-faysal-game-v2-32c09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1qhDHtM9Qz-KpHr9Adxzv99LPA336AQA',
    appId: '1:460415886376:ios:596d8f430b92605c55811d',
    messagingSenderId: '460415886376',
    projectId: 'flutter-faysal-game-v2-32c09',
    storageBucket: 'flutter-faysal-game-v2-32c09.firebasestorage.app',
    iosBundleId: 'com.example.flutterFaysalGame',
  );

}